### ISSUE TITLE
[Feature Request] - Stop backing services

### ISSUE THREAD

**Issue by co-pm** [alphagov/paas-roadmap#104]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is and the impact to you. Ex. I can't deploy x due to y being unavailable 
I would like to have a way to stop backing services when we stop the application. we have a service that is live only for few weeks in the year. When on AWS we would set instances to zero and we were not charged until we increase the instances back to 1 or more. With PaaS we can stop the app but we can not do the same with backing services.

**Is this blocking you from doing anything?**
A clear and concise description of any work that you are unable to complete.
Yes, as we will be paying for services that we will not be using

**Describe the outcome you'd like**
A clear and concise description of what you like to happen.
We would like to stop backing services

**Describe the solutions you've considered**
A clear and concise description of any solutions or features you've considered.
We had a solution on AWS (described above) but not on PaaS

**Additional context**

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.
http://govuk.zendesk.com/hc/requests/4603244

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by markpeterbuckley** [comment]
Hi Prashanth, unfortunately, this is a limitation of the platform and we are not able to make 'zero' possible in terms of backing services and so we can't offer this feature. As a work around, you would be able to take a snap shot/back up of the database and store that somewhere then delete the backing service and then reinstate the backing service at a later date if you know 'when' the service won't be needed. 

Is this an expanding need/use case for you because we are doing research at the moment into what direction hosting needs are going. If interested I would like to connect you to our researchers to understand your use cases and how we might approach these in the future. Let me know. Cheers, Mark.
