### ISSUE TITLE
[Feature Request] - GitHub Actions OIDC Authentication

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#106]
**Is your feature request related to a problem? Please describe.**

If I want to deploy to GOV.UK PaaS from GitHub Actions, I have to create a user in Cloud Foundry, and then store the username and password as secrets in GitHub Actions.

This is annoying to set up, and leads to a security risk if the password were to be leaked somehow. 

**Is this blocking you from doing anything?**

No, using username / password is totally sufficient. It just doesn't feel as slick or secure.

**Describe the outcome you'd like**

I would like to be able to authenticate from GitHub Actions to GOV.UK PaaS using [GitHub Actions' built in support for OIDC](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect).

I believe this should be possible, because PaaS already supports OIDC through UAA. Although I haven't thought through the details. CloudFoundry / UAA might not support the right OIDC flow. If not, you might have to fork it to add that functionality 😬 . There is documentation in UAA which covers [using the GitHub OIDC provider](https://github.com/cloudfoundry/uaa/blob/develop/docs/github-oauth2-provider.md).

**Describe the solutions you've considered**

Just using username / password authentication in GitHub secrets, just like everyone does now.

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by philandstuff** [comment]
IMO this doesn't have to be specific to GitHub Actions.  I think the underlying need is: "I need to assert the identity of a PaaS app instance to a third party, using temporary credentials, so that my app instance can access services without storing long-lived credentials that might get leaked or abused".

GitHub Actions supports this because GHA provides an OIDC provider, which you can use in AWS via sts:AssumeRoleWithWebIdentity. But you could do this with any OIDC provider, not just the GHA one.

On a related note, Cloud Foundry supports [instance identity credentials](https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html) which are an X.509 cert / private key pair.  If somehow this can be bodged into an OIDC shape, we could directly authenticate from Cloud Foundry to AWS without needing to rely on GHA at all.

**Comment by richardTowers** [comment]
Updated to add that there is some documentation in UAA on using the GitHub OIDC IdP - https://github.com/cloudfoundry/uaa/blob/develop/docs/github-oauth2-provider.md

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
