### ISSUE TITLE
Application autoscaling

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#17]
## Objective

Make it easier to autoscale applications running on GOV.UK PaaS

## Key results

* Validated assumptions around user needs
* It is easy for tenants to set up autoscaling of applications running on the PaaS
* Tenants are using it

## What we don’t know

* How people scale their apps
  * Queue length
  * CPU/Memory/Network IO

**Comment by matthewford** [comment]
I concur with @munhitsu CPU would be sufficient as a starting point.

**Comment by chrisfarms** [comment]
Looking at the knobs and dials available for AppEngine may be useful for this:

https://cloud.google.com/appengine/docs/standard/python/how-instances-are-managed

Autoscaling can be very application specific, but I found AppEngine's request/latency based scaling very intuitive for a wide range of applications, especially those where I wanted scale to zero.

**Comment by LeePorte** [comment]
Thank you for the updates on this. I have written a story to get [app-autoscaler](https://github.com/cloudfoundry/app-autoscaler) enabled on the platform. It provides a [good foundation set metrics on which to autoscale](https://github.com/cloudfoundry/app-autoscaler/tree/develop/docs) and has the advantage of being a Foundation blessed component. We have an upcoming backlog refinement and I expect that we should be able to get this enabled in the next couple of weeks.

Once it is deployed we'll drop you a line so that you can take it for a spin.

**Comment by tlwr** [comment]
Documentation preview: https://github.com/alphagov/paas-tech-docs/pull/334

Implementation preview: https://github.com/alphagov/paas-cf/pull/2408

**Comment by LeePorte** [comment]
Hi @matthewford, @munhitsu and @chrisfarms 

We have deployed this to both regions and have published the documentation over at https://docs.cloud.service.gov.uk/managing_apps.html#autoscaling. Take it for a spin and let us know how you get on with it
