### ISSUE TITLE
[Feature Request] - Aurora Serverless DB

### ISSUE THREAD

**Issue by gidsg** [alphagov/paas-roadmap#72]
**Is your feature request related to a problem? Please describe.** 
https://aws.amazon.com/rds/aurora/serverless/
Current instance types are less well cost optimised for certain use cases e.g. test environments, low traffic production environments, environments which receive short traffic spikes.

It would be good to not pay for idle databases on test environments.

It would be good if instances could autoscale in response to traffic spikes.

**Is this blocking you from doing anything?**
cost optimisation, rapid scaling

**Describe the outcome you'd like**
Aurora Serverless DB types available on marketplace

**Describe the solutions you've considered**
Existing DB types on marketplace

**Comment by LeePorte** [comment]
Hi Gids,

I can certainly see your use case and I can think of some other users where this would be handy. 

In order to enable this we need to some precursor work to enable dynamic billing as all of our current billing works on fixed service plans. Once we've got this bit cracked we'll be able to offer pay for usage backing services, We're hoping to have got the billing side delivered this quarter.

Cheers!

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
