### ISSUE TITLE
[Feature Request] - Add read-only user to RDS Postgres database instance managed by GOV.UK PaaS

### ISSUE THREAD

**Issue by markpeterbuckley** [alphagov/paas-roadmap#77]
**Is your feature request related to a problem? Please describe.**
Tenants need a way of enabling read-only access to Postgres databases in order to prevent changes and mistakes to databases.

**Is this blocking you from doing anything?**
Heightens risk of user error by having write access

**Describe the outcome you'd like**
You can bind with a read only user to RDS Postgres database instance managed by GOV.UK PaaS

**Describe the solutions you've considered**
Hard coding read only access in application code.

**References**
- ZENDESK-3857102

**Comment by markpeterbuckley** [comment]
See ZENDESK-3857102

**Comment by tlwr** [comment]
We're in the middle of implementing this and we have some product clarifications that we think would be helpful to get some user feedback on.

I'm writing these up but credit where credit is due to @barsutka @mogds and @chrisfarms for elucidating them in [the implementation PR](https://github.com/alphagov/paas-rds-broker/pull/117)

---

A roughly summarised user need is:

> As a user, I can `cf bind-service my-app my-svc -c '{"read_only": true}'` so that the binding will not be able to write to the database, only read from it, so that the binding can be used for reporting and examination safely.

Where we imagine several use cases:

* an operator or developer connecting to the database, to inspect the contents
* a business intelligence or analysis application which should only be able to perform reads, for security reasons
* an application that is designed around [CQRS](https://martinfowler.com/bliki/CQRS.html)

We are currently implementing this only for Postgres, however Postgres's permissions model prevents a naive implementation.

---

The default schema (`public`) for a Postgres database has default permissions for all users, this can only be changed by changing the default behaviour, which will affect some Postgres extensions which rely implicitly on the public schema.

This can be worked around by revoking all permissions but then re-adding them selectively, however this is likely not forward compatible with future Postgres versions and will cause the binding codepaths to be fragile.

We can use an event trigger to prevent DDL for the read only user only, which works as intended on multiple versions of Postgres (for both the public schema, and user created schemas), but we do not want tenants to rely on read only users as a security model ***in the `public` schema***. We are happy for it to be used as a read only security boundary for schemas other than `public` (***unless the schema is created in a way that grants permissive default permissions to all groups***).

---

We plan on:

- Granting usage and select to all schemas to all read only users
- Using an event trigger to prevent DDL for the read only user
- Documenting our concerns about use of the `public` schema in conjunction with read only users
- Documenting that Postgres schemas are powerful tools which will enable our users to increase their database security posture and permissions models, especially when used in conjunction with read only users

---

CC @munhitsu from the original Zendesk ticket

**Comment by risicle** [comment]
Could I guess that one such extension relying on `public` access would be postgis?

I'm not completely sure on how fragile re-adding default permissions to databases would be - I had to make minimal modifications to get my old PR https://github.com/alphagov/paas-rds-broker/pull/106 working happily from postgres 9.5 to ...11?

Do you really need to use event triggers to prevent DDL? Isn't this just a matter of not making them the owner of any of the objects?

**Comment by tlwr** [comment]
I think you have a more in-depth understanding of Postgres's permission models than I do, however I am concerned about touching `public` too much, and revoking all permissions, because this may impact extensions

The [Postgres documentation](https://www.postgresql.org/docs/9.4/sql-alterdefaultprivileges.html):
> per-schema default privileges can only add privileges to the global setting, not remove privileges granted by it

The way I plan on going forward:
- read only users are only granted usage and select to non-public schemas
- an event trigger prevent read only users to create schemas or tables in the public schema
- because the read only user does not own any objects, it cannot insert either

Functionally:
- a read only user cannot do any of [the things mentioned in the event trigger matrix](https://www.postgresql.org/docs/9.3/event-trigger-matrix.html) in any schema
- a read only user can only `SELECT` and `\d` from non-`public` schemas

**Comment by risicle** [comment]
Mhm ok so the event trigger is probably a useful addition...

I see your sneaky call to `make_readable()` on table creation etc. to avoid the requirement to rebind after schema changes, but I think you're also going to need to handle `CREATE VIEW`, `CREATE SEQUENCE` ... perhaps even `CREATE FUNCTION` and friends?
